/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BatchStatus = { 'filling' : null } |
  { 'cancelled' : null } |
  { 'full' : null } |
  { 'open' : null };
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'couponCode' : [] | [string],
  'participants' : Array<Participant>,
  'paymentStatus' : PaymentStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'gstAmount' : bigint,
  'totalAmount' : bigint,
  'addOns' : BookingAddOns,
  'trekSlug' : string,
  'stripePaymentIntentId' : [] | [string],
  'batchId' : bigint,
  'bookingRef' : string,
}
export interface BookingAddOns {
  'gearRental' : boolean,
  'cityPickup' : boolean,
  'insurance' : boolean,
  'singleRoom' : boolean,
  'photography' : boolean,
}
export interface BookingRequest {
  'status' : string,
  'participants' : bigint,
  'bookingId' : bigint,
  'tripName' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'tripId' : string,
  'nationality' : string,
  'email' : string,
  'phone' : string,
  'selectedDate' : string,
  'bookingRef' : string,
}
export interface BookingRequestInput {
  'participants' : bigint,
  'tripName' : string,
  'name' : string,
  'tripId' : string,
  'nationality' : string,
  'email' : string,
  'phone' : string,
  'selectedDate' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type Difficulty = { 'Easy' : null } |
  { 'EasyModerate' : null } |
  { 'Difficult' : null } |
  { 'Moderate' : null };
export interface FAQ { 'question' : string, 'answer' : string }
export interface GearRentalItem {
  'id' : bigint,
  'depositAmount' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'pricePerDay' : bigint,
}
export interface ItineraryDay {
  'meals' : [] | [string],
  'title' : string,
  'waypoints' : Array<string>,
  'altitude' : [] | [string],
  'description' : string,
  'accommodation' : [] | [string],
  'distanceKm' : [] | [number],
  'dayNumber' : bigint,
  'durationHrs' : [] | [number],
}
export interface Participant {
  'age' : bigint,
  'fitnessDeclaration' : boolean,
  'name' : string,
  'medicalConditions' : [] | [string],
  'emergencyContact' : string,
  'gender' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface Trek {
  'id' : string,
  'region' : string,
  'durationDays' : bigint,
  'country' : string,
  'packingList' : Array<string>,
  'faqs' : Array<FAQ>,
  'difficulty' : Difficulty,
  'isMostBooked' : boolean,
  'name' : string,
  'slug' : string,
  'description' : string,
  'inclusions' : Array<string>,
  'highlights' : Array<string>,
  'isEditorsPick' : boolean,
  'district' : [] | [string],
  'priceTo' : [] | [bigint],
  'state' : string,
  'imageUrl' : [] | [string],
  'maxAltitudeM' : bigint,
  'trekDistanceKm' : [] | [number],
  'exclusions' : Array<string>,
  'category' : TrekCategory,
  'priceFrom' : bigint,
  'endPoint' : [] | [string],
  'startPoint' : [] | [string],
  'isTrending' : boolean,
  'itinerary' : Array<ItineraryDay>,
  'youtubeVideoIds' : Array<string>,
  'bestSeason' : string,
}
export interface TrekBatch {
  'id' : bigint,
  'status' : BatchStatus,
  'endDate' : string,
  'pricePerPerson' : bigint,
  'totalSeats' : bigint,
  'bookedSeats' : bigint,
  'trekSlug' : string,
  'startDate' : string,
}
export type TrekCategory = { 'trek' : null } |
  { 'yatra' : null };
export interface Trip {
  'id' : string,
  'region' : string,
  'subRegion' : [] | [string],
  'duration' : bigint,
  'country' : string,
  'tripType' : string,
  'difficultyGrade' : bigint,
  'departureDate' : [] | [string],
  'isPremium' : boolean,
  'maxGroup' : bigint,
  'difficulty' : string,
  'name' : string,
  'slug' : string,
  'season' : Array<string>,
  'imageUrl' : [] | [string],
  'priceINR' : [] | [bigint],
  'priceUSD' : [] | [bigint],
  'maxAltitude' : bigint,
  'returnDate' : [] | [string],
  'isOnRequest' : boolean,
}
export interface WishlistItem {
  'userId' : Principal,
  'addedAt' : bigint,
  'trekSlug' : string,
}
export interface _SERVICE {
  'addToWishlist' : ActorMethod<[string], undefined>,
  'cancelBooking' : ActorMethod<[bigint], boolean>,
  'createBooking' : ActorMethod<
    [
      string,
      bigint,
      Array<Participant>,
      BookingAddOns,
      bigint,
      bigint,
      [] | [string],
    ],
    Booking
  >,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingById' : ActorMethod<[bigint], [] | [BookingRequest]>,
  'getGearRentalItems' : ActorMethod<[], Array<GearRentalItem>>,
  'getMyBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getMyTrekBookings' : ActorMethod<[], Array<Booking>>,
  'getMyWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'getTrekBatches' : ActorMethod<[string], Array<TrekBatch>>,
  'getTrekBySlug' : ActorMethod<[string], [] | [Trek]>,
  'getTreks' : ActorMethod<[], Array<Trek>>,
  'getTreksByDifficulty' : ActorMethod<[Difficulty], Array<Trek>>,
  'getTreksByState' : ActorMethod<[string], Array<Trek>>,
  'getTripBySlug' : ActorMethod<[string], [] | [Trip]>,
  'getTrips' : ActorMethod<[], Array<Trip>>,
  'getTripsByDifficulty' : ActorMethod<[string], Array<Trip>>,
  'getTripsByDuration' : ActorMethod<[string], Array<Trip>>,
  'getTripsByRegion' : ActorMethod<[string], Array<Trip>>,
  'getTripsBySeason' : ActorMethod<[string], Array<Trip>>,
  'getUpcomingBatchesForTrek' : ActorMethod<[string], Array<TrekBatch>>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'searchTreks' : ActorMethod<[string], Array<Trek>>,
  'submitBookingInquiry' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'submitBookingRequest' : ActorMethod<[BookingRequestInput], BookingRequest>,
  'submitCallbackRequest' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    bigint
  >,
  'submitContact' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      string,
    ],
    bigint
  >,
  'submitGHTInterest' : ActorMethod<
    [string, string, [] | [string], string, [] | [string]],
    bigint
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitTailorMade' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      string,
      [] | [string],
      string,
      [] | [string],
      string,
      [] | [string],
    ],
    bigint
  >,
  'subscribeNewsletter' : ActorMethod<[string], bigint>,
  'updateBookingPaymentStatus' : ActorMethod<
    [bigint, PaymentStatus, [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];