/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Participant = IDL.Record({
  'age' : IDL.Nat,
  'fitnessDeclaration' : IDL.Bool,
  'name' : IDL.Text,
  'medicalConditions' : IDL.Opt(IDL.Text),
  'emergencyContact' : IDL.Text,
  'gender' : IDL.Text,
});
export const BookingAddOns = IDL.Record({
  'gearRental' : IDL.Bool,
  'cityPickup' : IDL.Bool,
  'insurance' : IDL.Bool,
  'singleRoom' : IDL.Bool,
  'photography' : IDL.Bool,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'participants' : IDL.Vec(Participant),
  'paymentStatus' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'gstAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'addOns' : BookingAddOns,
  'trekSlug' : IDL.Text,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'batchId' : IDL.Nat,
  'bookingRef' : IDL.Text,
});
export const BookingRequest = IDL.Record({
  'status' : IDL.Text,
  'participants' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'tripName' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tripId' : IDL.Text,
  'nationality' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'selectedDate' : IDL.Text,
  'bookingRef' : IDL.Text,
});
export const GearRentalItem = IDL.Record({
  'id' : IDL.Nat,
  'depositAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
});
export const WishlistItem = IDL.Record({
  'userId' : IDL.Principal,
  'addedAt' : IDL.Int,
  'trekSlug' : IDL.Text,
});
export const BatchStatus = IDL.Variant({
  'filling' : IDL.Null,
  'cancelled' : IDL.Null,
  'full' : IDL.Null,
  'open' : IDL.Null,
});
export const TrekBatch = IDL.Record({
  'id' : IDL.Nat,
  'status' : BatchStatus,
  'endDate' : IDL.Text,
  'pricePerPerson' : IDL.Nat,
  'totalSeats' : IDL.Nat,
  'bookedSeats' : IDL.Nat,
  'trekSlug' : IDL.Text,
  'startDate' : IDL.Text,
});
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'EasyModerate' : IDL.Null,
  'Difficult' : IDL.Null,
  'Moderate' : IDL.Null,
});
export const TrekCategory = IDL.Variant({
  'trek' : IDL.Null,
  'yatra' : IDL.Null,
});
export const ItineraryDay = IDL.Record({
  'meals' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'waypoints' : IDL.Vec(IDL.Text),
  'altitude' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'accommodation' : IDL.Opt(IDL.Text),
  'distanceKm' : IDL.Opt(IDL.Float64),
  'dayNumber' : IDL.Nat,
  'durationHrs' : IDL.Opt(IDL.Float64),
});
export const Trek = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'durationDays' : IDL.Nat,
  'country' : IDL.Text,
  'packingList' : IDL.Vec(IDL.Text),
  'faqs' : IDL.Vec(FAQ),
  'difficulty' : Difficulty,
  'isMostBooked' : IDL.Bool,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'isEditorsPick' : IDL.Bool,
  'district' : IDL.Opt(IDL.Text),
  'priceTo' : IDL.Opt(IDL.Nat),
  'state' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'maxAltitudeM' : IDL.Nat,
  'trekDistanceKm' : IDL.Opt(IDL.Float64),
  'exclusions' : IDL.Vec(IDL.Text),
  'category' : TrekCategory,
  'priceFrom' : IDL.Nat,
  'endPoint' : IDL.Opt(IDL.Text),
  'startPoint' : IDL.Opt(IDL.Text),
  'isTrending' : IDL.Bool,
  'itinerary' : IDL.Vec(ItineraryDay),
  'youtubeVideoIds' : IDL.Vec(IDL.Text),
  'bestSeason' : IDL.Text,
});
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'subRegion' : IDL.Opt(IDL.Text),
  'duration' : IDL.Nat,
  'country' : IDL.Text,
  'tripType' : IDL.Text,
  'difficultyGrade' : IDL.Nat,
  'departureDate' : IDL.Opt(IDL.Text),
  'isPremium' : IDL.Bool,
  'maxGroup' : IDL.Nat,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'season' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'priceINR' : IDL.Opt(IDL.Nat),
  'priceUSD' : IDL.Opt(IDL.Nat),
  'maxAltitude' : IDL.Nat,
  'returnDate' : IDL.Opt(IDL.Text),
  'isOnRequest' : IDL.Bool,
});
export const BookingRequestInput = IDL.Record({
  'participants' : IDL.Nat,
  'tripName' : IDL.Text,
  'name' : IDL.Text,
  'tripId' : IDL.Text,
  'nationality' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'selectedDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Vec(Participant),
        BookingAddOns,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [Booking],
      [],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(BookingRequest)], ['query']),
  'getGearRentalItems' : IDL.Func([], [IDL.Vec(GearRentalItem)], ['query']),
  'getMyBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getMyTrekBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'getTrekBatches' : IDL.Func([IDL.Text], [IDL.Vec(TrekBatch)], ['query']),
  'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
  'getTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'getTreksByDifficulty' : IDL.Func([Difficulty], [IDL.Vec(Trek)], ['query']),
  'getTreksByState' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'getTripBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trip)], ['query']),
  'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getTripsByDifficulty' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'getTripsByDuration' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'getTripsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'getTripsBySeason' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'getUpcomingBatchesForTrek' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrekBatch)],
      ['query'],
    ),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'submitBookingInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitBookingRequest' : IDL.Func(
      [BookingRequestInput],
      [BookingRequest],
      [],
    ),
  'submitCallbackRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'submitContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'submitGHTInterest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitTailorMade' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'updateBookingPaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Participant = IDL.Record({
    'age' : IDL.Nat,
    'fitnessDeclaration' : IDL.Bool,
    'name' : IDL.Text,
    'medicalConditions' : IDL.Opt(IDL.Text),
    'emergencyContact' : IDL.Text,
    'gender' : IDL.Text,
  });
  const BookingAddOns = IDL.Record({
    'gearRental' : IDL.Bool,
    'cityPickup' : IDL.Bool,
    'insurance' : IDL.Bool,
    'singleRoom' : IDL.Bool,
    'photography' : IDL.Bool,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'participants' : IDL.Vec(Participant),
    'paymentStatus' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'gstAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'addOns' : BookingAddOns,
    'trekSlug' : IDL.Text,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'batchId' : IDL.Nat,
    'bookingRef' : IDL.Text,
  });
  const BookingRequest = IDL.Record({
    'status' : IDL.Text,
    'participants' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'tripName' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tripId' : IDL.Text,
    'nationality' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'selectedDate' : IDL.Text,
    'bookingRef' : IDL.Text,
  });
  const GearRentalItem = IDL.Record({
    'id' : IDL.Nat,
    'depositAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
  });
  const WishlistItem = IDL.Record({
    'userId' : IDL.Principal,
    'addedAt' : IDL.Int,
    'trekSlug' : IDL.Text,
  });
  const BatchStatus = IDL.Variant({
    'filling' : IDL.Null,
    'cancelled' : IDL.Null,
    'full' : IDL.Null,
    'open' : IDL.Null,
  });
  const TrekBatch = IDL.Record({
    'id' : IDL.Nat,
    'status' : BatchStatus,
    'endDate' : IDL.Text,
    'pricePerPerson' : IDL.Nat,
    'totalSeats' : IDL.Nat,
    'bookedSeats' : IDL.Nat,
    'trekSlug' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'EasyModerate' : IDL.Null,
    'Difficult' : IDL.Null,
    'Moderate' : IDL.Null,
  });
  const TrekCategory = IDL.Variant({ 'trek' : IDL.Null, 'yatra' : IDL.Null });
  const ItineraryDay = IDL.Record({
    'meals' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'waypoints' : IDL.Vec(IDL.Text),
    'altitude' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'accommodation' : IDL.Opt(IDL.Text),
    'distanceKm' : IDL.Opt(IDL.Float64),
    'dayNumber' : IDL.Nat,
    'durationHrs' : IDL.Opt(IDL.Float64),
  });
  const Trek = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'durationDays' : IDL.Nat,
    'country' : IDL.Text,
    'packingList' : IDL.Vec(IDL.Text),
    'faqs' : IDL.Vec(FAQ),
    'difficulty' : Difficulty,
    'isMostBooked' : IDL.Bool,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'isEditorsPick' : IDL.Bool,
    'district' : IDL.Opt(IDL.Text),
    'priceTo' : IDL.Opt(IDL.Nat),
    'state' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'maxAltitudeM' : IDL.Nat,
    'trekDistanceKm' : IDL.Opt(IDL.Float64),
    'exclusions' : IDL.Vec(IDL.Text),
    'category' : TrekCategory,
    'priceFrom' : IDL.Nat,
    'endPoint' : IDL.Opt(IDL.Text),
    'startPoint' : IDL.Opt(IDL.Text),
    'isTrending' : IDL.Bool,
    'itinerary' : IDL.Vec(ItineraryDay),
    'youtubeVideoIds' : IDL.Vec(IDL.Text),
    'bestSeason' : IDL.Text,
  });
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'subRegion' : IDL.Opt(IDL.Text),
    'duration' : IDL.Nat,
    'country' : IDL.Text,
    'tripType' : IDL.Text,
    'difficultyGrade' : IDL.Nat,
    'departureDate' : IDL.Opt(IDL.Text),
    'isPremium' : IDL.Bool,
    'maxGroup' : IDL.Nat,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'season' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'priceINR' : IDL.Opt(IDL.Nat),
    'priceUSD' : IDL.Opt(IDL.Nat),
    'maxAltitude' : IDL.Nat,
    'returnDate' : IDL.Opt(IDL.Text),
    'isOnRequest' : IDL.Bool,
  });
  const BookingRequestInput = IDL.Record({
    'participants' : IDL.Nat,
    'tripName' : IDL.Text,
    'name' : IDL.Text,
    'tripId' : IDL.Text,
    'nationality' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'selectedDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Vec(Participant),
          BookingAddOns,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [Booking],
        [],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BookingRequest)],
        ['query'],
      ),
    'getGearRentalItems' : IDL.Func([], [IDL.Vec(GearRentalItem)], ['query']),
    'getMyBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getMyTrekBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'getTrekBatches' : IDL.Func([IDL.Text], [IDL.Vec(TrekBatch)], ['query']),
    'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
    'getTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'getTreksByDifficulty' : IDL.Func([Difficulty], [IDL.Vec(Trek)], ['query']),
    'getTreksByState' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'getTripBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trip)], ['query']),
    'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getTripsByDifficulty' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'getTripsByDuration' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'getTripsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'getTripsBySeason' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'getUpcomingBatchesForTrek' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrekBatch)],
        ['query'],
      ),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'submitBookingInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitBookingRequest' : IDL.Func(
        [BookingRequestInput],
        [BookingRequest],
        [],
      ),
    'submitCallbackRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'submitContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'submitGHTInterest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitTailorMade' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'updateBookingPaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };