/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Participant {
    age: bigint;
    fitnessDeclaration: boolean;
    name: string;
    medicalConditions?: string;
    emergencyContact: string;
    gender: string;
}
export interface FAQ {
    question: string;
    answer: string;
}
export interface Trip {
    id: string;
    region: string;
    subRegion?: string;
    duration: bigint;
    country: string;
    tripType: string;
    difficultyGrade: bigint;
    departureDate?: string;
    isPremium: boolean;
    maxGroup: bigint;
    difficulty: string;
    name: string;
    slug: string;
    season: Array<string>;
    imageUrl?: string;
    priceINR?: bigint;
    priceUSD?: bigint;
    maxAltitude: bigint;
    returnDate?: string;
    isOnRequest: boolean;
}
export interface WishlistItem {
    userId: Principal;
    addedAt: bigint;
    trekSlug: string;
}
export interface Trek {
    id: string;
    region: string;
    durationDays: bigint;
    country: string;
    packingList: Array<string>;
    faqs: Array<FAQ>;
    difficulty: Difficulty;
    isMostBooked: boolean;
    name: string;
    slug: string;
    description: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    isEditorsPick: boolean;
    district?: string;
    priceTo?: bigint;
    state: string;
    imageUrl?: string;
    maxAltitudeM: bigint;
    trekDistanceKm?: number;
    exclusions: Array<string>;
    category: TrekCategory;
    priceFrom: bigint;
    endPoint?: string;
    startPoint?: string;
    isTrending: boolean;
    itinerary: Array<ItineraryDay>;
    youtubeVideoIds: Array<string>;
    bestSeason: string;
}
export interface BookingRequest {
    status: string;
    participants: bigint;
    bookingId: bigint;
    tripName: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    tripId: string;
    nationality: string;
    email: string;
    phone: string;
    selectedDate: string;
    bookingRef: string;
}
export interface ItineraryDay {
    meals?: string;
    title: string;
    waypoints: Array<string>;
    altitude?: string;
    description: string;
    accommodation?: string;
    distanceKm?: number;
    dayNumber: bigint;
    durationHrs?: number;
}
export interface BookingRequestInput {
    participants: bigint;
    tripName: string;
    name: string;
    tripId: string;
    nationality: string;
    email: string;
    phone: string;
    selectedDate: string;
}
export interface GearRentalItem {
    id: bigint;
    depositAmount: bigint;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
}
export interface TrekBatch {
    id: bigint;
    status: BatchStatus;
    endDate: string;
    pricePerPerson: bigint;
    totalSeats: bigint;
    bookedSeats: bigint;
    trekSlug: string;
    startDate: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    couponCode?: string;
    participants: Array<Participant>;
    paymentStatus: PaymentStatus;
    userId: Principal;
    createdAt: bigint;
    gstAmount: bigint;
    totalAmount: bigint;
    addOns: BookingAddOns;
    trekSlug: string;
    stripePaymentIntentId?: string;
    batchId: bigint;
    bookingRef: string;
}
export interface BookingAddOns {
    gearRental: boolean;
    cityPickup: boolean;
    insurance: boolean;
    singleRoom: boolean;
    photography: boolean;
}
export enum BatchStatus {
    filling = "filling",
    cancelled = "cancelled",
    full = "full",
    open = "open"
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum Difficulty {
    Easy = "Easy",
    EasyModerate = "EasyModerate",
    Difficult = "Difficult",
    Moderate = "Moderate"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum TrekCategory {
    trek = "trek",
    yatra = "yatra"
}
export interface backendInterface {
    addToWishlist(trekSlug: string): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<boolean>;
    createBooking(trekSlug: string, batchId: bigint, participants: Array<Participant>, addOns: BookingAddOns, totalAmount: bigint, gstAmount: bigint, couponCode: string | null): Promise<Booking>;
    getBooking(bookingId: bigint): Promise<Booking | null>;
    getBookingById(id: bigint): Promise<BookingRequest | null>;
    getGearRentalItems(): Promise<Array<GearRentalItem>>;
    getMyBookingRequests(): Promise<Array<BookingRequest>>;
    getMyTrekBookings(): Promise<Array<Booking>>;
    getMyWishlist(): Promise<Array<WishlistItem>>;
    getTrekBatches(trekSlug: string): Promise<Array<TrekBatch>>;
    getTrekBySlug(slug: string): Promise<Trek | null>;
    getTreks(): Promise<Array<Trek>>;
    getTreksByDifficulty(difficulty: Difficulty): Promise<Array<Trek>>;
    getTreksByState(state: string): Promise<Array<Trek>>;
    getTripBySlug(slug: string): Promise<Trip | null>;
    getTrips(): Promise<Array<Trip>>;
    getTripsByDifficulty(difficulty: string): Promise<Array<Trip>>;
    getTripsByDuration(durationRange: string): Promise<Array<Trip>>;
    getTripsByRegion(region: string): Promise<Array<Trip>>;
    getTripsBySeason(season: string): Promise<Array<Trip>>;
    getUpcomingBatchesForTrek(trekSlug: string): Promise<Array<TrekBatch>>;
    removeFromWishlist(trekSlug: string): Promise<void>;
    searchTreks(keyword: string): Promise<Array<Trek>>;
    submitBookingInquiry(tripId: string, name: string, email: string, message: string): Promise<bigint>;
    submitBookingRequest(input: BookingRequestInput): Promise<BookingRequest>;
    submitCallbackRequest(name: string, phone: string, trekInterest: string | null, preferredDate: string | null): Promise<bigint>;
    submitContact(name: string, email: string, phone: string | null, country: string | null, tripInterest: string | null, numberOfPeople: string | null, preferredDates: string | null, message: string): Promise<bigint>;
    submitGHTInterest(name: string, email: string, phone: string | null, ghtSection: string, message: string | null): Promise<bigint>;
    submitInquiry(trekSlug: string, name: string, email: string, phone: string, message: string): Promise<bigint>;
    submitTailorMade(name: string, email: string, phone: string | null, country: string | null, destination: string | null, numberOfPeople: string, preferredDuration: string | null, budgetRange: string, preferredDates: string | null, activityType: string, specialRequirements: string | null): Promise<bigint>;
    subscribeNewsletter(email: string): Promise<bigint>;
    updateBookingPaymentStatus(bookingId: bigint, paymentStatus: PaymentStatus, stripePaymentIntentId: string | null): Promise<boolean>;
}
import type { BatchStatus as _BatchStatus, Booking as _Booking, BookingAddOns as _BookingAddOns, BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, Difficulty as _Difficulty, FAQ as _FAQ, ItineraryDay as _ItineraryDay, Participant as _Participant, PaymentStatus as _PaymentStatus, Trek as _Trek, TrekBatch as _TrekBatch, TrekCategory as _TrekCategory, Trip as _Trip } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWishlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: string, arg1: bigint, arg2: Array<Participant>, arg3: BookingAddOns, arg4: bigint, arg5: bigint, arg6: string | null): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: bigint): Promise<BookingRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGearRentalItems(): Promise<Array<GearRentalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGearRentalItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGearRentalItems();
            return result;
        }
    }
    async getMyBookingRequests(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookingRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookingRequests();
            return result;
        }
    }
    async getMyTrekBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTrekBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTrekBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWishlist(): Promise<Array<WishlistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWishlist();
            return result;
        }
    }
    async getTrekBatches(arg0: string): Promise<Array<TrekBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrekBatches(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrekBatches(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrekBySlug(arg0: string): Promise<Trek | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrekBySlug(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrekBySlug(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreks(): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreks();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreks();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreksByDifficulty(arg0: Difficulty): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreksByDifficulty(to_candid_Difficulty_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreksByDifficulty(to_candid_Difficulty_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreksByState(arg0: string): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreksByState(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreksByState(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripBySlug(arg0: string): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripBySlug(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripBySlug(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrips();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrips();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripsByDifficulty(arg0: string): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripsByDifficulty(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripsByDifficulty(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripsByDuration(arg0: string): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripsByDuration(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripsByDuration(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripsByRegion(arg0: string): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripsByRegion(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripsByRegion(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripsBySeason(arg0: string): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripsBySeason(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripsBySeason(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingBatchesForTrek(arg0: string): Promise<Array<TrekBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingBatchesForTrek(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingBatchesForTrek(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async searchTreks(arg0: string): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTreks(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTreks(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBookingInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitBookingRequest(arg0: BookingRequestInput): Promise<BookingRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingRequest(arg0);
            return result;
        }
    }
    async submitCallbackRequest(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCallbackRequest(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCallbackRequest(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async submitGHTInterest(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGHTInterest(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGHTInterest(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitTailorMade(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string, arg6: string | null, arg7: string, arg8: string | null, arg9: string, arg10: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTailorMade(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTailorMade(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async subscribeNewsletter(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return result;
        }
    }
    async updateBookingPaymentStatus(arg0: bigint, arg1: PaymentStatus, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingPaymentStatus(arg0, to_candid_PaymentStatus_n42(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingPaymentStatus(arg0, to_candid_PaymentStatus_n42(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_BatchStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStatus): BatchStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ItineraryDay_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItineraryDay): ItineraryDay {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Participant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Participant): Participant {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TrekBatch_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrekBatch): TrekBatch {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TrekCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrekCategory): TrekCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Trek_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trek): Trek {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingRequest]): BookingRequest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trek]): Trek | null {
    return value.length === 0 ? null : from_candid_Trek_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    fitnessDeclaration: boolean;
    name: string;
    medicalConditions: [] | [string];
    emergencyContact: string;
    gender: string;
}): {
    age: bigint;
    fitnessDeclaration: boolean;
    name: string;
    medicalConditions?: string;
    emergencyContact: string;
    gender: string;
} {
    return {
        age: value.age,
        fitnessDeclaration: value.fitnessDeclaration,
        name: value.name,
        medicalConditions: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.medicalConditions)),
        emergencyContact: value.emergencyContact,
        gender: value.gender
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BatchStatus;
    endDate: string;
    pricePerPerson: bigint;
    totalSeats: bigint;
    bookedSeats: bigint;
    trekSlug: string;
    startDate: string;
}): {
    id: bigint;
    status: BatchStatus;
    endDate: string;
    pricePerPerson: bigint;
    totalSeats: bigint;
    bookedSeats: bigint;
    trekSlug: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_BatchStatus_n21(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        pricePerPerson: value.pricePerPerson,
        totalSeats: value.totalSeats,
        bookedSeats: value.bookedSeats,
        trekSlug: value.trekSlug,
        startDate: value.startDate
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    durationDays: bigint;
    country: string;
    packingList: Array<string>;
    faqs: Array<_FAQ>;
    difficulty: _Difficulty;
    isMostBooked: boolean;
    name: string;
    slug: string;
    description: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    isEditorsPick: boolean;
    district: [] | [string];
    priceTo: [] | [bigint];
    state: string;
    imageUrl: [] | [string];
    maxAltitudeM: bigint;
    trekDistanceKm: [] | [number];
    exclusions: Array<string>;
    category: _TrekCategory;
    priceFrom: bigint;
    endPoint: [] | [string];
    startPoint: [] | [string];
    isTrending: boolean;
    itinerary: Array<_ItineraryDay>;
    youtubeVideoIds: Array<string>;
    bestSeason: string;
}): {
    id: string;
    region: string;
    durationDays: bigint;
    country: string;
    packingList: Array<string>;
    faqs: Array<FAQ>;
    difficulty: Difficulty;
    isMostBooked: boolean;
    name: string;
    slug: string;
    description: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    isEditorsPick: boolean;
    district?: string;
    priceTo?: bigint;
    state: string;
    imageUrl?: string;
    maxAltitudeM: bigint;
    trekDistanceKm?: number;
    exclusions: Array<string>;
    category: TrekCategory;
    priceFrom: bigint;
    endPoint?: string;
    startPoint?: string;
    isTrending: boolean;
    itinerary: Array<ItineraryDay>;
    youtubeVideoIds: Array<string>;
    bestSeason: string;
} {
    return {
        id: value.id,
        region: value.region,
        durationDays: value.durationDays,
        country: value.country,
        packingList: value.packingList,
        faqs: value.faqs,
        difficulty: from_candid_Difficulty_n26(_uploadFile, _downloadFile, value.difficulty),
        isMostBooked: value.isMostBooked,
        name: value.name,
        slug: value.slug,
        description: value.description,
        inclusions: value.inclusions,
        highlights: value.highlights,
        isEditorsPick: value.isEditorsPick,
        district: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.district)),
        priceTo: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.priceTo)),
        state: value.state,
        imageUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageUrl)),
        maxAltitudeM: value.maxAltitudeM,
        trekDistanceKm: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.trekDistanceKm)),
        exclusions: value.exclusions,
        category: from_candid_TrekCategory_n30(_uploadFile, _downloadFile, value.category),
        priceFrom: value.priceFrom,
        endPoint: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.endPoint)),
        startPoint: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.startPoint)),
        isTrending: value.isTrending,
        itinerary: from_candid_vec_n32(_uploadFile, _downloadFile, value.itinerary),
        youtubeVideoIds: value.youtubeVideoIds,
        bestSeason: value.bestSeason
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: [] | [string];
    title: string;
    waypoints: Array<string>;
    altitude: [] | [string];
    description: string;
    accommodation: [] | [string];
    distanceKm: [] | [number];
    dayNumber: bigint;
    durationHrs: [] | [number];
}): {
    meals?: string;
    title: string;
    waypoints: Array<string>;
    altitude?: string;
    description: string;
    accommodation?: string;
    distanceKm?: number;
    dayNumber: bigint;
    durationHrs?: number;
} {
    return {
        meals: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.meals)),
        title: value.title,
        waypoints: value.waypoints,
        altitude: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.altitude)),
        description: value.description,
        accommodation: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.accommodation)),
        distanceKm: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.distanceKm)),
        dayNumber: value.dayNumber,
        durationHrs: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.durationHrs))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    subRegion: [] | [string];
    duration: bigint;
    country: string;
    tripType: string;
    difficultyGrade: bigint;
    departureDate: [] | [string];
    isPremium: boolean;
    maxGroup: bigint;
    difficulty: string;
    name: string;
    slug: string;
    season: Array<string>;
    imageUrl: [] | [string];
    priceINR: [] | [bigint];
    priceUSD: [] | [bigint];
    maxAltitude: bigint;
    returnDate: [] | [string];
    isOnRequest: boolean;
}): {
    id: string;
    region: string;
    subRegion?: string;
    duration: bigint;
    country: string;
    tripType: string;
    difficultyGrade: bigint;
    departureDate?: string;
    isPremium: boolean;
    maxGroup: bigint;
    difficulty: string;
    name: string;
    slug: string;
    season: Array<string>;
    imageUrl?: string;
    priceINR?: bigint;
    priceUSD?: bigint;
    maxAltitude: bigint;
    returnDate?: string;
    isOnRequest: boolean;
} {
    return {
        id: value.id,
        region: value.region,
        subRegion: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.subRegion)),
        duration: value.duration,
        country: value.country,
        tripType: value.tripType,
        difficultyGrade: value.difficultyGrade,
        departureDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.departureDate)),
        isPremium: value.isPremium,
        maxGroup: value.maxGroup,
        difficulty: value.difficulty,
        name: value.name,
        slug: value.slug,
        season: value.season,
        imageUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageUrl)),
        priceINR: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.priceINR)),
        priceUSD: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.priceUSD)),
        maxAltitude: value.maxAltitude,
        returnDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.returnDate)),
        isOnRequest: value.isOnRequest
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    couponCode: [] | [string];
    participants: Array<_Participant>;
    paymentStatus: _PaymentStatus;
    userId: Principal;
    createdAt: bigint;
    gstAmount: bigint;
    totalAmount: bigint;
    addOns: _BookingAddOns;
    trekSlug: string;
    stripePaymentIntentId: [] | [string];
    batchId: bigint;
    bookingRef: string;
}): {
    id: bigint;
    status: BookingStatus;
    couponCode?: string;
    participants: Array<Participant>;
    paymentStatus: PaymentStatus;
    userId: Principal;
    createdAt: bigint;
    gstAmount: bigint;
    totalAmount: bigint;
    addOns: BookingAddOns;
    trekSlug: string;
    stripePaymentIntentId?: string;
    batchId: bigint;
    bookingRef: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n7(_uploadFile, _downloadFile, value.status),
        couponCode: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.couponCode)),
        participants: from_candid_vec_n10(_uploadFile, _downloadFile, value.participants),
        paymentStatus: from_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.paymentStatus),
        userId: value.userId,
        createdAt: value.createdAt,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        addOns: value.addOns,
        trekSlug: value.trekSlug,
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.stripePaymentIntentId)),
        batchId: value.batchId,
        bookingRef: value.bookingRef
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filling: null;
} | {
    cancelled: null;
} | {
    full: null;
} | {
    open: null;
}): BatchStatus {
    return "filling" in value ? BatchStatus.filling : "cancelled" in value ? BatchStatus.cancelled : "full" in value ? BatchStatus.full : "open" in value ? BatchStatus.open : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    EasyModerate: null;
} | {
    Difficult: null;
} | {
    Moderate: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "EasyModerate" in value ? Difficulty.EasyModerate : "Difficult" in value ? Difficulty.Difficult : "Moderate" in value ? Difficulty.Moderate : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trek: null;
} | {
    yatra: null;
}): TrekCategory {
    return "trek" in value ? TrekCategory.trek : "yatra" in value ? TrekCategory.yatra : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Participant>): Array<Participant> {
    return value.map((x)=>from_candid_Participant_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrekBatch>): Array<TrekBatch> {
    return value.map((x)=>from_candid_TrekBatch_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ItineraryDay>): Array<ItineraryDay> {
    return value.map((x)=>from_candid_ItineraryDay_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trek>): Array<Trek> {
    return value.map((x)=>from_candid_Trek_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n39(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Participant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Participant): _Participant {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    fitnessDeclaration: boolean;
    name: string;
    medicalConditions?: string;
    emergencyContact: string;
    gender: string;
}): {
    age: bigint;
    fitnessDeclaration: boolean;
    name: string;
    medicalConditions: [] | [string];
    emergencyContact: string;
    gender: string;
} {
    return {
        age: value.age,
        fitnessDeclaration: value.fitnessDeclaration,
        name: value.name,
        medicalConditions: value.medicalConditions ? candid_some(value.medicalConditions) : candid_none(),
        emergencyContact: value.emergencyContact,
        gender: value.gender
    };
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Easy: null;
} | {
    EasyModerate: null;
} | {
    Difficult: null;
} | {
    Moderate: null;
} {
    return value == Difficulty.Easy ? {
        Easy: null
    } : value == Difficulty.EasyModerate ? {
        EasyModerate: null
    } : value == Difficulty.Difficult ? {
        Difficult: null
    } : value == Difficulty.Moderate ? {
        Moderate: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Participant>): Array<_Participant> {
    return value.map((x)=>to_candid_Participant_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
